### PR TITLE
setup npm workspaces, moved project to lib/destack, created nextjs pr…

### PR DESCRIPTION
**Pull request by LiveDuo**
With this PR it's significantly easier to setup the project for local development.

See [CONTRIBUTING.md](https://github.com/LiveDuo/destack/blob/migration/npm-workspaces/CONTRIBUTING.md)!

### CODE REVIEW

**Comment by JcdeA** [comment]
This looks great, but what do you think about renaming lib/destack to pkg/destack.

Or would removing the ./lib dir and putting it in the library in src be better? I think the code structure would be a bit confusing for newcomers.

I suggest something like this:

Src/ -  destack source
Dev/nextjs-project - nextjs app for dev

We could move the src directory(currently inside ./lib/destack/src) to something like ./src/browser/

~~Ugg autocorrect sucks for writing software related stuff~~

**Comment by LiveDuo** [comment]
Sure, something to consider. 

I'm not aware of what the convention is or it might just be too early for such a convention as NPM workspaces launched just a few months ago. Will have to look into further.

Everything seems smooth so far but will need more tests before publishing to NPM. If you encounter any issues open an issue or let me know.

**Comment by JcdeA** [comment]
Thanks

**Comment by JcdeA** [comment]
Looks like yarn workspaces are a bit different to npm's. Npm allows workspaces to be enabled without being private, but yarn workspaces are meant to be only used privately. I might have to use npm for this project.

**Comment by JcdeA** [comment]
I'm having some problems with npm workspaces..
doesn't seem to work very well for me..

**Pull request merged**
